name: petsapp
description: "PetsApp with Home, Buy (view all, details, wishlist), Sell form, and Help."
publish_to: "none"
version: 3.2.0+23

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  http: ^1.2.0
  intl: ^0.20.2
  image_picker: ^1.2.0
  video_player: ^2.9.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.1
  geocoding: ^2.1.1
  flutter_launcher_icons: ^0.14.1
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

  

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  flavors:
    dev:
      image_path: "assets/icons/app_icon_dev.png"
    prod:
      image_path: "assets/icons/app_icon_prod.png"

  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"
